from framework.pages.base_page import BasePage
from framework.components.header.main_header_component import MainHeaderComponent

from framework.components.header.main_menu_component import MainMenuComponent
from framework.components.header.user_menu_component import UserMenuComponent
